name: Quarto Site Deploy

on:
  push:
    branches:
      - main   # Trigger on pushes to main

jobs:
  build-deploy:
    runs-on: macos-latest

    steps:
      # 1. Check out the repository
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Install Quarto
      - name: Install Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.3.371' # adjust to the latest Quarto version

      # 3. Render the site
      - name: Render Quarto site
        run: quarto render

      # 4. Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
