project:
  type: website

website:
  title: "Statistical Rethinking Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ch4_linear_regression_polished.qmd
        text: Linear Regression
      - href: forkingData.qmd
        text: Forking Paths
format:
  html:
    theme: cosmo
    toc: true