project:
  type: website

website:
  title: "Statistical Rethinking Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: ch4_linear_regression_polished.qmd
        text: Linear Regression
      - href: ch5_multilinear.qmd
        text: Multi Regression
      - href: ch6_DAG.qmd
        text: Causal Paths
format:
  html:
    theme: cosmo
    toc: true