project:
  type: website

website:
  title: "Jaden's Statistical Rethinking"
  navbar:
    left:
      - href: ch4_linear_regression_polished.qmd
        text: Linear Regression
      - href: ch5_multilinear.qmd
        text: Multi Regression
      - href: ch6_DAG.qmd
        text: Causal Confounds
      - href: ch7ModelComparison.qmd
        text: Model Metrics
      - href: ch8_conditional.qmd
        text: Interactions
        
format:
  html:
    theme: cosmo
    toc: true